name: EvoCraft
version: '${project.version}'
main: me.zenox.evocraft.EvoCraft
api-version: 1.20
authors: [ ZenoX ]
description: Transforms your game into an highly specialized MMORPG experience.
softdepend: [ Citizens, WorldGuard, WorldEdit ]
depend: [ AureliumSkills, ProtocolLib, ModelEngine, Vault ]

commands:
  evocraft:
    aliases: [ evc, ec, evo ]
    description: Base command for EvoCraft
    usage: /evocraft
    permission: evocraft.admin
