name: SuperItems
version: '${project.version}'
main: me.zenox.superitems.SuperItems
api-version: 1.19
authors: [ ZenoX ]
description: Implements custom hypixel inspired items!
softdepend: [WorldGuard, WorldEdit]
depend:
  - AureliumSkills

commands:
  superitems:
    aliases: [ si ]
    description: Base command for SuperItems
    usage: /si
    permission: superitems.admin
